"""Додано таблицю учасників аукціонів і поле total_earnings

Revision ID: 587ae8603977
Revises: 1ef04d1ecd3c
Create Date: 2024-12-08 13:25:43.978244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '587ae8603977'
down_revision = '1ef04d1ecd3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auctions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_earnings', sa.Float, nullable=False, server_default="0"))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auctions', schema=None) as batch_op:
        batch_op.drop_column('total_earnings')

    # ### end Alembic commands ###
