"""Add platform balance to User

Revision ID: 9a60bba3a089
Revises: 2f0182222f89
Create Date: 2024-12-10 17:29:26.244932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a60bba3a089'
down_revision = '2f0182222f89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform_balance', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('platform_balance')

    # ### end Alembic commands ###
